#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-22h"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "2f2d6508a9534642b0f36d4659e147cc" }
]

[assets]
directory = "./public"
